### PR TITLE
[Fix] Original Affirm implementation didn't need to check for billing…

### PR DESCRIPTION
**Pull request by DeveloperMetal**
… causing issues on changes that came later

- Adds billing completion check
- Adds awc embed form api to handle billing address check
- Adds affirm "You will be redirected to affirm" message when selecting the affirm gateway

I am not merging this myself, as we should probably have a few more eyes testing this on staging. Also, this doesn't fix the permission issue last reported as I was unable to reproduce

affirm-billing-fix

^ sorry about the shitty gif quality

### **This pr requires changes on the gateway selector: https://github.com/DigiThinkIT/gateway_selector/pull/40**

### CODE REVIEW

**Comment by Alchez** [comment]
Pulled both the PRs and put Affirm on Sandbox mode.

I keep getting the following error when it's trying to redirect to Affirm:
image

Tried debugging it, but no luck.

**Comment by DeveloperMetal** [comment]
was the "You are in dev mode" banner displaying on that window?

**Comment by Alchez** [comment]
99

**Comment by Alchez** [comment]
No, this wasn't even on Affirm. This error popped up on the JHA cart.

I've updated the image.

**Comment by DeveloperMetal** [comment]
Check your keys, you need separate keys form sandbox mode. Mine starts with: 9CK and xu3

**Review by Alchez — APPROVED** [review]

**Comment by Alchez** [comment]
Yeah, the sandbox keys worked fine. :+1:

**Pull request merged**
